# -*- coding: utf-8 -*-
"""1.4. Домашняя работа Сергей Шутов, группа 93

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1yFSpwBCBqsjA0oNHgBHqn6792u_fopnD
"""

# высадка в нормандии, звезда смерти на горизонте, танки на омаха бич, сепия ,историческое фото
createImagesStableDiffusion('Normandy landings, DeathStar on the horizon, tanks on the omaha beach, sepia, historical photo, –ar 16:9 ', 2, 2, 100)

# извержение вулкана Везувий, fireworks, Thanksgiving Day parade
createImagesStableDiffusion('eruption of Mount Vesuvius, fireworks, Thanksgiving Day parade, 4K –ar 16:9 ', 2, 2, 100)

# запуск атомного реактора, праздник с пуншем, в стиле Айвазовского
createImagesStableDiffusion('Nuclear reactor launch, punch party, Aivazovsky-style, high detail, 4K –ar 16:9 ', 2, 2, 100)

# пещера горного короля, в стиле фентези, призрак комунизма ходит по пещере
createImagesStableDiffusion('The cave of the mountain king, fantasy style, the ghost of communism walks through the cave, high detail, 4K –ar 16:9 ', 2, 2, 100)

# высокотехнологичное производство сковородок, роботы, микрочипы, футуризм, высокая детализация
createImagesStableDiffusion('high-tech frying pan production, robots, microchips, futurism,, high detail, 4K –ar 16:9 ', 2, 2, 100)